name: Publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "22"
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-turbo-
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install deps
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Lint
        run: pnpm lint
      - name: Test
        run: pnpm test
  publish:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        node-version:
          - "22"
    steps:
      - uses: actions/checkout@v5
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@d17247dd94ca7b39d0b0691399be8d7c510622c9
        with:
          diff-search: true
          file-name: ./package.json
      - uses: actions/cache@v4
        if: steps.check.outputs.changed == 'true'
        with:
          path: .turbo
          key: ${{ runner.os }}-${{ matrix.node-version }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-turbo-
      - uses: pnpm/action-setup@v4
        if: steps.check.outputs.changed == 'true'
      - name: Setup Node.js ${{ matrix.node-version }}
        if: steps.check.outputs.changed == 'true'
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
      - name: Install deps
        if: steps.check.outputs.changed == 'true'
        run: pnpm install
      - name: Build
        if: steps.check.outputs.changed == 'true'
        run: pnpm build
      - name: Publish
        if: steps.check.outputs.changed == 'true'
        run: |
          pnpm publish --no-git-checks --access=public --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_AUTOMATION_TOKEN }}
          NPM_CONFIG_PROVENANCE: "true"
